version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: retro-mike-dozzle_web_1
      APP_PORT: 8080

  web:
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: on-failure
